accelerator: gpu
devices: 1
default_root_dir: ./logs
num_nodes: 1
num_sanity_val_steps: 0
precision: 16-mixed
max_epochs: 4
check_val_every_n_epoch: 2
reload_dataloaders_every_n_epochs: 1
log_every_n_steps: 20
