name: salad_dinov2b14
backbone_arch: dinov2_vitb14
backbone_config:
  num_trainable_blocks: 4
  return_token: true
  norm_layer: true
agg_arch: SALAD
agg_config:
  num_channels: 768
  num_clusters: 64
  cluster_dim: 128
  token_dim: 256
lr: 6e-5
optimizer: adamw
weight_decay: 9.5e-9
momentum: 0.9
lr_sched: linear
lr_sched_args:
  start_factor: 1
  end_factor: 0.2
  total_iters: 4000
loss_name: MultiSimilarityLoss
miner_name: MultiSimilarityMiner
miner_margin: 0.1
faiss_gpu: false
